// AUTO-GENERATED by scripts/generate.js — do not edit manually
const { executeAsync } = require('./index');

describe('Go DLL exports', () => {
  test('executeAsync resolves to a string', async () => {
    const result = await executeAsync("test1");
    expect(typeof result).toBe('string');
    expect(result.length).toBeGreaterThan(0);
  }, 10000);
});
