// AUTO-GENERATED by scripts/generate.js — do not edit manually
const addon = require('bindings')('addon');

async function executeAsync(input) {
  const result = await addon.executeAsyncPromise(input);
  return `${result}`;
}

module.exports = { executeAsync };
