#!/usr/bin/env node
/**
 * Parses //export annotations in include/main.go and generates:
 *   addon.cc       — C++ AsyncWorker per exported function
 *   index.js       — async JS wrappers
 *   index.d.ts     — TypeScript declarations
 *   index.test.js  — Jest tests (string-return sanity check)
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const GO_FILE  = path.join(ROOT, 'include', 'main.go');
const ADDON_CC = path.join(ROOT, 'addon.cc');
const INDEX_JS = path.join(ROOT, 'index.js');
const INDEX_DTS = path.join(ROOT, 'index.d.ts');
const TEST_JS  = path.join(ROOT, 'index.test.js');

// ── parser ────────────────────────────────────────────────────────────────────

function parseGoExports(filePath) {
  const lines = fs.readFileSync(filePath, 'utf-8').split(/\r?\n/);
  const funcs = [];

  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(/^\/\/export\s+(\w+)/);
    if (!m) continue;
    const goName = m[1];

    for (let j = i + 1; j < lines.length; j++) {
      const line = lines[j].trim();
      if (!line) continue;
      const sig = line.match(/^func\s+\w+\(([^)]*)\)\s*(.*)?$/);
      if (sig) {
        const paramsStr = sig[1].trim();
        const params = paramsStr
          ? paramsStr.split(',').map((p, idx) => {
              const parts = p.trim().split(/\s+/);
              return { name: parts[0] || `param${idx}`, ctype: parts.slice(1).join(' ') };
            })
          : [];
        funcs.push({ goName, params });
      }
      break;
    }
  }
  return funcs;
}

// ── naming ────────────────────────────────────────────────────────────────────

const toCamel = s => s.charAt(0).toLowerCase() + s.slice(1);

// ── addon.cc generators ───────────────────────────────────────────────────────

function workerClass(f) {
  const cls = `${f.goName}Worker`;
  const n = f.params.length;

  const memberDecls = f.params.map(p => `  std::string ${p.name}_;`).join('\n');

  const ctorParams = n === 0
    ? 'Napi::Env env, Napi::Promise::Deferred deferred'
    : `Napi::Env env, ${f.params.map(p => `std::string ${p.name}`).join(', ')}, Napi::Promise::Deferred deferred`;

  const ctorInit = n === 0
    ? ': Napi::AsyncWorker(env), deferred_(deferred)'
    : `: Napi::AsyncWorker(env), ${f.params.map(p => `${p.name}_(${p.name})`).join(', ')}, deferred_(deferred)`;

  const cParamTypes = f.params.map(() => 'const char *').join(', ');
  const callArgs = f.params.map(p => `${p.name}_.c_str()`).join(', ');

  return `
class ${cls} : public Napi::AsyncWorker
{
public:
  ${cls}(${ctorParams})
      ${ctorInit} {}

  void Execute() override
  {
    EnsureDLLLoaded();
    FARPROC pFunc = GetProcAddress(g_hDLL, "${f.goName}");
    if (!pFunc)
    {
      error_ = "Failed to find function in DLL: ${f.goName}";
      return;
    }
    typedef const char *(*FuncType)(${cParamTypes});
    FuncType dllFunction = reinterpret_cast<FuncType>(pFunc);
    const char *res = dllFunction(${callArgs});
    if (res)
    {
      result_ = res;
      free((void *)res);
    }
    else
    {
      error_ = "DLL function returned null";
    }
  }

  void OnOK() override
  {
    Napi::HandleScope scope(Env());
    if (error_.empty())
    {
      deferred_.Resolve(Napi::String::New(Env(), result_));
    }
    else
    {
      deferred_.Reject(Napi::Error::New(Env(), error_).Value());
    }
  }

  void OnError(const Napi::Error &e) override
  {
    Napi::HandleScope scope(Env());
    deferred_.Reject(e.Value());
  }

private:
${memberDecls ? memberDecls + '\n' : ''}  std::string result_;
  std::string error_;
  Napi::Promise::Deferred deferred_;
};`;
}

function wrapperFn(f) {
  const jsName = toCamel(f.goName);
  const cls = `${f.goName}Worker`;
  const n = f.params.length;

  const argChecks = n === 0 ? '' : `
  if (info.Length() < ${n})
  {
    Napi::TypeError::New(env, "${n} argument(s) expected").ThrowAsJavaScriptException();
    return env.Null();
  }
${f.params.map((p, i) => `  std::string ${p.name} = info[${i}].As<Napi::String>().Utf8Value();`).join('\n')}`;

  const workerArgs = n === 0
    ? 'env, deferred'
    : `env, ${f.params.map(p => p.name).join(', ')}, deferred`;

  return `
Napi::Value ${jsName}Promise(const Napi::CallbackInfo &info)
{
  Napi::Env env = info.Env();${argChecks}
  Napi::Promise::Deferred deferred = Napi::Promise::Deferred::New(env);
  (new ${cls}(${workerArgs}))->Queue();
  return deferred.Promise();
}`;
}

function generateAddonCC(funcs) {
  const initEntries = funcs
    .map(f => {
      const jsName = toCamel(f.goName);
      return `  exports.Set(Napi::String::New(env, "${jsName}Promise"),\n              Napi::Function::New(env, ${jsName}Promise));`;
    })
    .join('\n');

  return `// AUTO-GENERATED by scripts/generate.js — do not edit manually
#include <napi.h>
#include <windows.h>
#include <string>

HMODULE g_hDLL = nullptr;

void EnsureDLLLoaded()
{
  if (!g_hDLL)
  {
    g_hDLL = LoadLibraryA("include/goshared.dll");
  }
}
${funcs.map(workerClass).join('\n')}
${funcs.map(wrapperFn).join('\n')}

Napi::Object Init(Napi::Env env, Napi::Object exports)
{
${initEntries}
  return exports;
}

NODE_API_MODULE(addon, Init)
`;
}

// ── index.js ──────────────────────────────────────────────────────────────────

function generateIndexJS(funcs) {
  const fns = funcs.map(f => {
    const jsName = toCamel(f.goName);
    const args = f.params.map(p => p.name).join(', ');
    return `async function ${jsName}(${args}) {
  const result = await addon.${jsName}Promise(${args});
  return \`\${result}\`;
}`;
  });

  return `// AUTO-GENERATED by scripts/generate.js — do not edit manually
const addon = require('bindings')('addon');

${fns.join('\n\n')}

module.exports = { ${funcs.map(f => toCamel(f.goName)).join(', ')} };
`;
}

// ── index.d.ts ────────────────────────────────────────────────────────────────

function generateIndexDTS(funcs) {
  const lines = funcs.map(f => {
    const jsName = toCamel(f.goName);
    const paramList = f.params.map(p => `${p.name}: string`).join(', ');
    return `export function ${jsName}(${paramList}): Promise<string>;`;
  });

  return `// AUTO-GENERATED by scripts/generate.js — do not edit manually
${lines.join('\n')}
`;
}

// ── index.test.js ─────────────────────────────────────────────────────────────

function generateTestJS(funcs) {
  const importList = funcs.map(f => toCamel(f.goName)).join(', ');

  const tests = funcs.map(f => {
    const jsName = toCamel(f.goName);
    const args = f.params.map((_, i) => `"test${i + 1}"`).join(', ');
    return `  test('${jsName} resolves to a string', async () => {
    const result = await ${jsName}(${args});
    expect(typeof result).toBe('string');
    expect(result.length).toBeGreaterThan(0);
  }, 10000);`;
  });

  return `// AUTO-GENERATED by scripts/generate.js — do not edit manually
const { ${importList} } = require('./index');

describe('Go DLL exports', () => {
${tests.join('\n\n')}
});
`;
}

// ── main ──────────────────────────────────────────────────────────────────────

const funcs = parseGoExports(GO_FILE);
if (funcs.length === 0) {
  console.error('No //export functions found in', GO_FILE);
  process.exit(1);
}

console.log(`Found ${funcs.length} exported function(s): ${funcs.map(f => f.goName).join(', ')}`);

fs.writeFileSync(ADDON_CC, generateAddonCC(funcs));
console.log('  generated addon.cc');

fs.writeFileSync(INDEX_JS, generateIndexJS(funcs));
console.log('  generated index.js');

fs.writeFileSync(INDEX_DTS, generateIndexDTS(funcs));
console.log('  generated index.d.ts');

fs.writeFileSync(TEST_JS, generateTestJS(funcs));
console.log('  generated index.test.js');
